### PR TITLE
Added Comments for function explanation

### PR DESCRIPTION
**Pull request by sinarest1608**
This adds comments to explain the functions

Refer #4

### CODE REVIEW

**Review by mbentz-uf — CHANGES_REQUESTED** [review]
Unfortunately with the latest changes from PR #10, this PR will need to be updated. When you add comments can you use python doc strings? [peps.python.org](https://peps.python.org/pep-0257/) has good information on this, specifically the "Multi-line Docstrings" section.

**Comment by sinarest1608** [comment]
@mbentz-uf 
Sure, I'll resolve the conflicts and add comments to the new code as well. I would also make sure to use python doc strings and replace the existing `#` comments with that.

**Comment by sinarest1608** [comment]
@mbentz-uf 
Keeping this on hold until https://github.com/ctsit/report_handler/pull/11 is merged since it's the same file that needs to be updated and this PR would have conflicts again. Working on https://github.com/ctsit/report_handler/pull/11 now.

**Comment by sinarest1608** [comment]
@mbentz-uf 
I think the Readme also needs to be updated since https://github.com/ctsit/report_handler/pull/11 was merged.
Should I add the changes to the Readme here itself or create a separate issue for that?

**Review by mbentz-uf — CHANGES_REQUESTED** [review]
For writing docstrings can you follow the example in this [gist](https://gist.github.com/mbentz-uf/0433c32f260a0a06f57a9ff32fcef252).

**Comment by mbentz-uf** [comment]
> @mbentz-uf I think the Readme also needs to be updated since #11 was merged. Should I add the changes to the Readme here itself or create a separate issue for that?

Yes please include those updates in here as well.

**Pull request merged**
